config/routes.rb
Rails.application.routes.draw do
  get "tasks/index"
  get "tasks/show"
  get "tasks/new"
  get "tasks/edit/:id", to: "tasks#edit", as: "tasks_edit"
  get "tasks/create"
  get "tasks/update"
  get "tasks/destroy/:id", to: "tasks#destroy", as: "tasks_destroy"
  resources :tasks
  namespace :home do
    get "index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :completion_status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.order(created_at: :desc)

    if params[:query].present?
      query = "%#{params[:query].downcase}%"
      @tasks = Task.where("LOWER(title) LIKE ? OR LOWER(description) LIKE ?", query, query)
    end

    if params[:status].present?
      status_value = AppConstants::STATUS[params[:status].to_sym]
      @tasks = @tasks.where(completion_status: status_value) if status_value
    end
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :edit, :update, :destroy ]
  def index
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to home_index_path
    else
      render :new, notice: "Not all required fields entered."
    end
  end

  def edit
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
        redirect_to home_index_path
    else
      render :edit, notice: "Not all required fields entered."
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to home_index_path, notice: "Task was successfully deleted."
  end

  private
  def set_task
    @task = Task.find_by("id" => params[:id])
  end

  def task_params
    params.require(:task).permit(:id, :title, :description, :completion_status, :completed_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/create.html.erb
<h1>create page</h1>
<div class="col-sm-12 col-md-6 col-lg-4 mb-4">
    <div class="card text-dark card-has-bg click-col"
        style="background-image:url('https://source.unsplash.com/600x900/?tech,street');">
        <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
            <div class="card-body">
                <small class="card-meta mb-2">placeholder</small>
                <%# <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">PLACEHOLDER</a></h4> %>
                <small><i class="far fa-clock"></i>placeholder</small>
            </div>
            <div class="card-footer">
                <div class="media">
                    <img class="mr-3 rounded-circle" src="" alt="" style="max-width:50px; min-width:75px; min-height:75px;">
                    <div class="media-body">
                        <div>
                            <h6 class="my-0 text-dark d-block">Priority</h6>
                            <small>PLACEHOLDER</small>
                        </div>
                        <%# <i class="fa fa-plus-circle"></i> %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/edit.html.erb
<h1>edit page</h1>
<%= form_with model: @task do |form| %>
<div class="col-sm-12 col-md-6 col-lg-4 mb-4">
    <div class="card text-dark card-has-bg click-col"
        style="background-image:url('https://source.unsplash.com/600x900/?tech,street');">
        <img class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street" alt="Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?">
        <div class="card-img-overlay d-flex flex-column">
            <div class="card-body">
                <small><%=form.text_area :title, class: "card-meta mb-2 field_input"%></small>
                <%# <h4 class="card-title mt-0 "><a class="text-dark" herf="https://creativemanner.com">PLACEHOLDER</a></h4> %>
                <small><%=form.text_area :description, class: "field_input"%></small>
            </div>
            <div class="card-footer">
                <div class="media">
                    <img class="mr-3 rounded-circle" src="" alt="" style="max-width:50px; min-width:75px; min-height:75px;">
                    <div class="media-body">
                        <div>
                            <h6 class="my-0 text-dark d-block">Priority</h6>
                            <small>PLACEHOLDER</small>
                        </div>
                        <%# <i class="fa fa-plus-circle"></i> %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <%= form.submit "Update"%>
</div>
<%end%>

app/views/home/index.html.haml
%div
  = link_to tasks_new_path, class: "btn btn-lg", style: "font-size: 3em; color: #e3f2fd; position: fixed; margin-top: -10px;", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "Create a new task" do
    %i.fa.fa-plus-circle.icon-grow

%section.wrapper{ style: "min-height: 500px" }
  .container.py-2
    .row
      - @tasks.each do |task|
        = render "shared/card", task: task

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "To Do List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/header"%>
    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/shared/_card.html.haml
.col-sm-12.col-md-6.col-lg-4.mb-4
  .card.text-dark.card-has-bg.click-col{ style: "background-image:url('https://source.unsplash.com/600x900/?tech,street');" }
    %img.card-img.d-none{ src: "https://source.unsplash.com/600x900/?tech,street", alt: "Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?" }
    .card-img-overlay.d-flex.flex-column
      .card-body
        %small.card-meta.mb-2= task["title"]
        %small= task["description"]
      .card-footer
        .media.d-flex.flex-column.gap-2
          .mr-3.rounded-circle.d-flex.justify-content-center.align-items-center{ style: "width:4rem; height:4rem ;border:2px solid limegreen" }
            - if task.completion_status == AppConstants::STATUS[:PENDING]
              %i.fa.fa-battery-empty{ style: "color:limegreen; font-size: 2em", aria: { hidden: "true" } }
            - if task.completion_status == AppConstants::STATUS[:STARTED]
              %i.fa.fa-battery-half{ style: "color:limegreen; font-size: 2em", aria: { hidden: "true" } }
            - if task.completion_status == AppConstants::STATUS[:COMPLETED]
              %i.fa.fa-battery-full{ style: "color:limegreen; font-size: 2em", aria: { hidden: "true" } }
          .media-body.d-flex.flex-row.justify-content-between.align-items-center
            - if task.updated_at == task.created_at
              %div
                %small
                  %i Created
                %small= task.created_at.strftime("%B %d, %Y")
            - elsif task.updated_at != task.created_at
              %div
                %small
                  %i Updated
                %small= task.updated_at.strftime("%B %d, %Y")
            .d-flex.flex-row.justify-content-end.gap-4
              = link_to tasks_edit_path(task), style: "font-size: 1.5em; color: rgba(0,0,0,0.3);", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "Edit task" do
                %i.fa.fa-pencil
              = link_to tasks_destroy_path(task), style: "font-size: 1.5em; color: rgba(0,0,0,0.3);", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "Delete task" do
                %i.fa.fa-trash-o

app/views/shared/_footer.html.haml
%link{rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"}
%footer.mt-auto
  .container
    .row
      .col-md-4.mb-3
        %h5 About Us
        %p Our passion is for you to do your best. We provide the best in class To Do application to keep you orginized and productive.
      .col-md-4.mb-3
        %h5 Quick Links
        %ul.list-unstyled
          %li
            %a.text-decoration-none.text-white{href: "#"} Home
      .col-md-4.mb-3
        %h5 Follow Us
        %ul.list-inline.social-icons
          %li.list-inline-item
            %a.text-white{href: "https://www.linkedin.com/company/fait-distribution"}
              %i.fa.fa-linkedin-square
    %hr.mb-4
    .row
      .col-md-12.text-center
        %p &copy; 2025 To Do Your Best. All rights reserved.

app/views/shared/_header.html.haml
%nav.navbar.sticky-top.navbar-expand-lg.navbar-light{ style: "background-color: #e3f2fd;" }
  .container-fluid
    = link_to "/", class: "navbar-brand" do
      TO DO
    %button.navbar-toggler{ type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#navbarCollapse" }
      %span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      .navbar-nav
      .navbar-nav.ms-auto.align-items-center.gap-3
        - AppConstants::STATUS.each do |key, value|
          - icon_class = case key
            - when :PENDING then 'fa-battery-empty'
            - when :STARTED then 'fa-battery-half'
            - when :COMPLETED then 'fa-battery-full'
          = link_to home_index_path(query: params[:query], status: key), class: "text-decoration-none" do
            %i{ class: "fa #{icon_class}", style: "color:limegreen; font-size: 2em;", "aria-hidden": "true" }

        = form_with url: home_index_path, method: :get, local: true do
          .d-flex.ms-auto
            = text_field_tag :query, params[:query], class: "form-control me-sm-2", placeholder: "Search"
            = submit_tag "Search", class: "btn btn-outline-primary"

app/views/tasks/edit.html.haml
.col-sm-12.col-md-6.col-lg-4.mb-4.p-5
  = form_with(model: @task, local: true) do |form|
    .card.text-dark.card-has-bg.click-col{style: "background-image:url('https://source.unsplash.com/600x900/?tech,street');"}
      %img.card-img.d-none{src: "https://source.unsplash.com/600x900/?tech,street", alt: "Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?"}
      .card-img-overlay.d-flex.flex-column
        .card-body
          %small= form.text_area :title, class: "card-meta mb-2 field_input", rows: 3
          %small= form.text_area :description, class: "field_input", rows: 7
        .card-footer
          .media.d-flex.flex-column.gap-2
            .d-flex.flex-row.justify-content-start.gap-2{"data-controller" => "tasks"}
              - AppConstants::STATUS.each do |key, value|
                - icon_class = case key
                  - when :PENDING then 'fa-battery-empty'
                  - when :STARTED then 'fa-battery-half'
                  - when :COMPLETED then 'fa-battery-full'
                %label.mr-3{"data-value" => value, style: "cursor: pointer;"}
                  = form.radio_button :completion_status, value, checked: @task.completion_status == value, data: {action: "change->tasks#checked"}
                  .rounded-circle.d-flex.justify-content-center.align-items-center{style: "width:3rem; height:3rem; border:2px solid grey;"}
                    %i{"class" => "fa #{icon_class}", style: "color:limegreen; font-size: 1.5em;", "aria-hidden" => "true"}
            .media-body.d-flex.flex-row.justify-content-between.align-items-center
              %div
                - if @task.updated_at == @task.created_at
                  %small
                    %i Created
                  %small= @task.created_at.strftime("%B %d, %Y")
                - elsif @task.updated_at != @task.created_at
                  %div
                    %small
                      %i Updated
                    %small= @task.updated_at.strftime("%B %d, %Y")
              %div
                = button_tag(type: 'submit', class: 'btn btn-outline-primary', id: "updateButton", disabled: false) do
                  Update

app/views/tasks/index.html.haml
%h1 Tasks#index 
%p Find me in app/views/tasks/index.html.haml

app/views/tasks/new.html.haml
= form_with(model: @task, local: true) do |form|
  .col-sm-12.col-md-6.col-lg-4.mb-4.p-5
    .card.text-dark.card-has-bg.click-col{ style: "background-image:url('https://source.unsplash.com/600x900/?tech,street');" }
      %img.card-img.d-none{ src: "https://source.unsplash.com/600x900/?tech,street", alt: "Creative Manner Design Lorem Ipsum Sit Amet Consectetur dipisi?" }
      .card-img-overlay.d-flex.flex-column
        .card-body
          %small= form.text_area :title, placeholder: "Enter a title", class: "card-meta mb-2 field_input", rows: 3
          %small= form.text_area :description, placeholder: "Enter a description", class: "field_input", rows: 7
        .card-footer
          .media.d-flex.flex-column.gap-2
            .d-flex.flex-row.justify-content-start.gap-2{ data: { controller: "tasks" } }
              - AppConstants::STATUS.each do |key, value|
                - icon_class = case key
                  - when :PENDING then 'fa-battery-empty'
                  - when :STARTED then 'fa-battery-half'
                  - when :COMPLETED then 'fa-battery-full'
                %label.mr-3{ data: { value: value }, style: "cursor: pointer;" }
                  = form.radio_button :completion_status, value, checked: @task.completion_status == value, data: { action: "change->tasks#checked" }
                  .rounded-circle.d-flex.justify-content-center.align-items-center{ style: "width:3rem; height:3rem; border:2px solid grey;" }
                    %i{ class: "fa #{icon_class}", style: "color:limegreen; font-size: 1.5em;", "aria-hidden": "true" }
            .media-body.d-flex.flex-row.justify-content-between.align-items-center
              %div
              %div
                = button_tag(type: 'submit', class: 'btn btn-outline-primary', disabled: false) do
                  Create

app/views/tasks/show.html.haml
%h1 Tasks#show
%p find me in app/views/tasks/show.html.haml